//cryptos list
cryptoList = [
	{
		name: "bitcoin",
		symbol: "btc",
		icon: "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400",
	},
	{
		name: "Ethereum",
		symbol: "eth",
		icon: "https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628",
	},
	{
		name: "Tether",
		symbol: "usdt",
		icon: "https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661",
	},
	{
		name: "Binancecoin",
		symbol: "bnb",
		icon: "https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970",
	},
	{
		name: "Dogecoin",
		symbol: "doge",
		icon: "https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409",
	},
	{
		name: "Tron",
		symbol: "trx",
		icon: "https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193",
	},
	{
		name: "Bitcoin-cash",
		symbol: "bch",
		icon: "https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932",
	},
	{
		name: "Polkadot",
		symbol: "dot",
		icon: "https://coin-images.coingecko.com/coins/images/12171/large/polkadot.png?1696512008",
	},
	{
		name: "Notcoin",
		symbol: "not",
		icon: "https://coin-images.coingecko.com/coins/images/33453/small/rFmThDiD_400x400.jpg?1701876350",
	},
	{
		name: "Usd-coin",
		symbol: "usdc",
		icon: "https://coin-images.coingecko.com/coins/images/6319/large/usdc.png?1696506694",
	},
	{
		name: "Solana",
		symbol: "sol",
		icon: "https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756",
	},
	{
		name: "Ripple",
		symbol: "xrp",
		icon: "https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442",
	},
	{
		name: "Staked-ether",
		symbol: "steth",
		icon: "https://coin-images.coingecko.com/coins/images/13442/large/steth_logo.png?1696513206",
	},
	{
		name: "Silver",
		symbol: "silver",
		icon: "https://coin-images.coingecko.com/coins/images/32273/small/LOGO1.png?1697179980",
	},
	{
		name: "Dai",
		symbol: "dai",
		icon: "https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996",
	},
	{
		name: "Litecoin",
		symbol: "ltc",
		icon: "https://coin-images.coingecko.com/coins/images/2/large/litecoin.png?1696501400",
	},
	{
		name: "Catizen",
		symbol: "cati",
		icon: "https://coin-images.coingecko.com/coins/images/50236/small/cati.png?1726638258",
	},
	{
		name: "Celestia",
		symbol: "tia",
		icon: "https://coin-images.coingecko.com/coins/images/31967/large/tia.jpg?1696530772",
	},
	{
		name: "Hamster-kombat",
		symbol: "hmstr",
		icon: "https://coin-images.coingecko.com/coins/images/39102/large/hamster-removebg-preview.png?1720514486",
	},
	{
		name: "Baby-doge-coin",
		symbol: "babydoge",
		icon: "https://coin-images.coingecko.com/coins/images/16125/large/babydoge.jpg?1696515731",
	},
];
//currencies list
let currenciesList = [
	{
		currency: "USD",
		country: "Dollar (United States)",
		symbol: "$",
		countryCode: "US",
		currencyName: "Dollar",
	},
	{
		currency: "AED",
		country: "Dirham (United Arab)",
		symbol: "د.إ",
		countryCode: "AE",
		currencyName: "Dirham",
	},
	{
		currency: "AFN",
		country: "Afghani (Afghanistan)",
		symbol: "؋",
		countryCode: "AF",
		currencyName: "Afghani",
	},
	{
		currency: "ALL",
		country: "Lek (Albania)",
		symbol: "L",
		countryCode: "AL",
		currencyName: "Lek",
	},
	{
		currency: "AMD",
		country: "Dram (Armenia)",
		symbol: "֏",
		countryCode: "AM",
		currencyName: "Dram",
	},
	{
		currency: "AOA",
		country: "Kwanza (Angola)",
		symbol: "Kz",
		countryCode: "AO",
		currencyName: "Kwanza",
	},
	{
		currency: "ARS",
		country: "Peso (Argentina)",
		symbol: "$",
		countryCode: "AR",
		currencyName: "Peso",
	},
	{
		currency: "AUD",
		country: "Dollar (Australia)",
		symbol: "$",
		countryCode: "AU",
		currencyName: "Dollar",
	},
	{
		currency: "AWG",
		country: "Florin (Aruba)",
		symbol: "ƒ",
		countryCode: "AW",
		currencyName: "Florin",
	},
	{
		currency: "AZN",
		country: "Manat (Azerbaijan)",
		symbol: "₼",
		countryCode: "AZ",
		currencyName: "Manat",
	},
	{
		currency: "BAM",
		country: "Mark (Bosnia)",
		symbol: "KM",
		countryCode: "BA",
		currencyName: "Mark",
	},
	{
		currency: "BBD",
		country: "Dollar (Barbados)",
		symbol: "$",
		countryCode: "BB",
		currencyName: "Dollar",
	},
	{
		currency: "BDT",
		country: "Taka (Bangladesh)",
		symbol: "৳",
		countryCode: "BD",
		currencyName: "Taka",
	},
	{
		currency: "BGN",
		country: "Lev (Bulgaria)",
		symbol: "лв",
		countryCode: "BG",
		currencyName: "Lev",
	},
	{
		currency: "BHD",
		country: "Dinar (Bahrain)",
		symbol: ".د.ب",
		countryCode: "BH",
		currencyName: "Dinar",
	},
	{
		currency: "BIF",
		country: "Franc (Burundi)",
		symbol: "FBu",
		countryCode: "BI",
		currencyName: "Franc",
	},
	{
		currency: "BMD",
		country: "Dollar (Bermuda)",
		symbol: "$",
		countryCode: "BM",
		currencyName: "Dollar",
	},
	{
		currency: "BND",
		country: "Dollar (Brunei)",
		symbol: "$",
		countryCode: "BN",
		currencyName: "Dollar",
	},
	{
		currency: "BOB",
		country: "Boliviano (Bolivia)",
		symbol: "Bs.",
		countryCode: "BO",
		currencyName: "Boliviano",
	},
	{
		currency: "BRL",
		country: "Real (Brazil)",
		symbol: "R$",
		countryCode: "BR",
		currencyName: "Real",
	},
	{
		currency: "BSD",
		country: "Dollar (Bahamas)",
		symbol: "$",
		countryCode: "BS",
		currencyName: "Dollar",
	},
	{
		currency: "BTN",
		country: "Ngultrum (Bhutan)",
		symbol: "Nu.",
		countryCode: "BT",
		currencyName: "Ngultrum",
	},
	{
		currency: "BWP",
		country: "Pula (Botswana)",
		symbol: "P",
		countryCode: "BW",
		currencyName: "Pula",
	},
	{
		currency: "BYN",
		country: "Ruble (Belarus)",
		symbol: "Br",
		countryCode: "BY",
		currencyName: "Ruble",
	},
	{
		currency: "BZD",
		country: "Dollar (Belize)",
		symbol: "$",
		countryCode: "BZ",
		currencyName: "Dollar",
	},
	{
		currency: "CAD",
		country: "Dollar (Canada)",
		symbol: "$",
		countryCode: "CA",
		currencyName: "Dollar",
	},
	{
		currency: "CDF",
		country: "Franc (Congo)",
		symbol: "FC",
		countryCode: "CD",
		currencyName: "Franc",
	},
	{
		currency: "CHF",
		country: "Franc (Switzerland)",
		symbol: "CHF",
		countryCode: "CH",
		currencyName: "Franc",
	},
	{
		currency: "CLP",
		country: "Peso (Chile)",
		symbol: "$",
		countryCode: "CL",
		currencyName: "Peso",
	},
	{
		currency: "CNY",
		country: "Yuan (China)",
		symbol: "¥",
		countryCode: "CN",
		currencyName: "Yuan",
	},
	{
		currency: "COP",
		country: "Peso (Colombia)",
		symbol: "$",
		countryCode: "CO",
		currencyName: "Peso",
	},
	{
		currency: "CRC",
		country: "Colon (Rica)",
		symbol: "₡",
		countryCode: "CR",
		currencyName: "Colon",
	},
	{
		currency: "CUP",
		country: "Peso (Cuba)",
		symbol: "$",
		countryCode: "CU",
		currencyName: "Peso",
	},
	{
		currency: "CVE",
		country: "Escudo (Verde)",
		symbol: "$",
		countryCode: "CV",
		currencyName: "Escudo",
	},
	{
		currency: "CZK",
		country: "Koruna (Republic)",
		symbol: "Kč",
		countryCode: "CZ",
		currencyName: "Koruna",
	},
	{
		currency: "DJF",
		country: "Franc (Djibouti)",
		symbol: "Fdj",
		countryCode: "DJ",
		currencyName: "Franc",
	},
	{
		currency: "DKK",
		country: "Krone (Denmark)",
		symbol: "kr",
		countryCode: "DK",
		currencyName: "Krone",
	},
	{
		currency: "DOP",
		country: "Peso (Dominican)",
		symbol: "RD$",
		countryCode: "DO",
		currencyName: "Peso",
	},
	{
		currency: "DZD",
		country: "Dinar (Algeria)",
		symbol: "دج",
		countryCode: "DZ",
		currencyName: "Dinar",
	},
	{
		currency: "EGP",
		country: "Pound (Egypt)",
		symbol: "£",
		countryCode: "EG",
		currencyName: "Pound",
	},
	{
		currency: "ERN",
		country: "Nakfa (Eritrea)",
		symbol: "Nfk",
		countryCode: "ER",
		currencyName: "Nakfa",
	},
	{
		currency: "ETB",
		country: "Birr (Ethiopia)",
		symbol: "Br",
		countryCode: "ET",
		currencyName: "Birr",
	},
	{
		currency: "FJD",
		country: "Dollar (Fiji)",
		symbol: "$",
		countryCode: "FJ",
		currencyName: "Dollar",
	},
	{
		currency: "FKP",
		country: "Pound (Falkland)",
		symbol: "£",
		countryCode: "FK",
		currencyName: "Pound",
	},
	{
		currency: "FOK",
		country: "Krone (Faroe)",
		symbol: "kr",
		countryCode: "FO",
		currencyName: "Krone",
	},
	{
		currency: "GBP",
		country: "Pound (Kingdom)",
		symbol: "£",
		countryCode: "GB",
		currencyName: "Pound",
	},
	{
		currency: "GEL",
		country: "Lari (Georgia)",
		symbol: "₾",
		countryCode: "GE",
		currencyName: "Lari",
	},
	{
		currency: "GGP",
		country: "Pound (Guernsey)",
		symbol: "£",
		countryCode: "GG",
		currencyName: "Pound",
	},
	{
		currency: "GHS",
		country: "Cedi (Ghana)",
		symbol: "₵",
		countryCode: "GH",
		currencyName: "Cedi",
	},
	{
		currency: "GIP",
		country: "Pound (Gibraltar)",
		symbol: "£",
		countryCode: "GI",
		currencyName: "Pound",
	},
	{
		currency: "GMD",
		country: "Dalasi (Gambia)",
		symbol: "D",
		countryCode: "GM",
		currencyName: "Dalasi",
	},
	{
		currency: "GNF",
		country: "Franc (Guinea)",
		symbol: "FG",
		countryCode: "GN",
		currencyName: "Franc",
	},
	{
		currency: "GTQ",
		country: "Quetzal (Guatemala)",
		symbol: "Q",
		countryCode: "GT",
		currencyName: "Quetzal",
	},
	{
		currency: "GYD",
		country: "Dollar (Guyana)",
		symbol: "$",
		countryCode: "GY",
		currencyName: "Dollar",
	},
	{
		currency: "HKD",
		country: "Dollar (Hong Kong)",
		symbol: "$",
		countryCode: "HK",
		currencyName: "Dollar",
	},
	{
		currency: "HNL",
		country: "Lempira (Honduras)",
		symbol: "L",
		countryCode: "HN",
		currencyName: "Lempira",
	},
	{
		currency: "HRK",
		country: "Kuna (Croatia)",
		symbol: "kn",
		countryCode: "HR",
		currencyName: "Kuna",
	},
	{
		currency: "HTG",
		country: "Gourde (Haiti)",
		symbol: "G",
		countryCode: "HT",
		currencyName: "Gourde",
	},
	{
		currency: "HUF",
		country: "Forint (Hungary)",
		symbol: "Ft",
		countryCode: "HU",
		currencyName: "Forint",
	},
	{
		currency: "IDR",
		country: "Rupiah (Indonesia)",
		symbol: "Rp",
		countryCode: "ID",
		currencyName: "Rupiah",
	},
	{
		currency: "ILS",
		country: "Shekel (Israel)",
		symbol: "₪",
		countryCode: "IL",
		currencyName: "Shekel",
	},
	{
		currency: "INR",
		country: "Rupee (India)",
		symbol: "₹",
		countryCode: "IN",
		currencyName: "Rupee",
	},
	{
		currency: "IQD",
		country: "Dinar (Iraq)",
		symbol: "ع.د",
		countryCode: "IQ",
		currencyName: "Dinar",
	},
	{
		currency: "IRR",
		country: "Rial (Iran)",
		symbol: "﷼",
		countryCode: "IR",
		currencyName: "Rial",
	},
	{
		currency: "ISK",
		country: "Krona (Iceland)",
		symbol: "kr",
		countryCode: "IS",
		currencyName: "Krona",
	},
	{
		currency: "JMD",
		country: "Dollar (Jamaica)",
		symbol: "$",
		countryCode: "JM",
		currencyName: "Dollar",
	},
	{
		currency: "JPY",
		country: "Yen (Japan)",
		symbol: "¥",
		countryCode: "JP",
		currencyName: "Yen",
	},
	{
		currency: "KES",
		country: "Shilling (Kenya)",
		symbol: "KSh",
		countryCode: "KE",
		currencyName: "Shilling",
	},
	{
		currency: "KGS",
		country: "Som (Kyrgyzstan)",
		symbol: "с",
		countryCode: "KG",
		currencyName: "Som",
	},
	{
		currency: "KHR",
		country: "Riel (Cambodia)",
		symbol: "៛",
		countryCode: "KH",
		currencyName: "Riel",
	},
	{
		currency: "KPW",
		country: "Won (North Korea)",
		symbol: "₩",
		countryCode: "KP",
		currencyName: "Won",
	},
	{
		currency: "KRW",
		country: "Won (South Korea)",
		symbol: "₩",
		countryCode: "KR",
		currencyName: "Won",
	},
	{
		currency: "KWD",
		country: "Dinar (Kuwait)",
		symbol: "د.ك",
		countryCode: "KW",
		currencyName: "Dinar",
	},
	{
		currency: "KYD",
		country: "Dollar (Cayman)",
		symbol: "$",
		countryCode: "KY",
		currencyName: "Dollar",
	},
	{
		currency: "KZT",
		country: "Tenge (Kazakhstan)",
		symbol: "₸",
		countryCode: "KZ",
		currencyName: "Tenge",
	},
	{
		currency: "LAK",
		country: "Kip (Laos)",
		symbol: "₭",
		countryCode: "LA",
		currencyName: "Kip",
	},
	{
		currency: "LBP",
		country: "Pound (Lebanon)",
		symbol: "ل.ل",
		countryCode: "LB",
		currencyName: "Pound",
	},
	{
		currency: "LKR",
		country: "Rupee (Sri Lanka)",
		symbol: "Rs",
		countryCode: "LK",
		currencyName: "Rupee",
	},
	{
		currency: "LRD",
		country: "Dollar (Liberia)",
		symbol: "$",
		countryCode: "LR",
		currencyName: "Dollar",
	},
	{
		currency: "LYD",
		country: "Dinar (Libya)",
		symbol: "ل.د",
		countryCode: "LY",
		currencyName: "Dinar",
	},
	{
		currency: "MAD",
		country: "Dirham (Morocco)",
		symbol: "د.م.",
		countryCode: "MA",
		currencyName: "Dirham",
	},
	{
		currency: "MDL",
		country: "Leu (Moldova)",
		symbol: "L",
		countryCode: "MD",
		currencyName: "Leu",
	},
	{
		currency: "MGA",
		country: "Ariary (Madagascar)",
		symbol: "Ar",
		countryCode: "MG",
		currencyName: "Ariary",
	},
	{
		currency: "MKD",
		country: "Denar (Macedonia)",
		symbol: "ден",
		countryCode: "MK",
		currencyName: "Denar",
	},
	{
		currency: "MMK",
		country: "Kyat (Myanmar)",
		symbol: "K",
		countryCode: "MM",
		currencyName: "Kyat",
	},
	{
		currency: "MNT",
		country: "Tögrög (Mongolia)",
		symbol: "₮",
		countryCode: "MN",
		currencyName: "Tögrög",
	},
	{
		currency: "MRU",
		country: "Ouguiya (Mauritania)",
		symbol: "UM",
		countryCode: "MR",
		currencyName: "Ouguiya",
	},
	{
		currency: "MUR",
		country: "Rupee (Mauritius)",
		symbol: "₨",
		countryCode: "MU",
		currencyName: "Rupee",
	},
	{
		currency: "MVR",
		country: "Rufiyaa (Maldives)",
		symbol: "MVR",
		countryCode: "MV",
		currencyName: "Rufiyaa",
	},
	{
		currency: "MWK",
		country: "Kwacha (Malawi)",
		symbol: "MK",
		countryCode: "MW",
		currencyName: "Kwacha",
	},
	{
		currency: "MXN",
		country: "Peso (Mexico)",
		symbol: "$",
		countryCode: "MX",
		currencyName: "Peso",
	},
	{
		currency: "MYR",
		country: "Ringgit (Malaysia)",
		symbol: "RM",
		countryCode: "MY",
		currencyName: "Ringgit",
	},
	{
		currency: "MZN",
		country: "Metical (Mozambique)",
		symbol: "MT",
		countryCode: "MZ",
		currencyName: "Metical",
	},
	{
		currency: "NAD",
		country: "Dollar (Namibia)",
		symbol: "$",
		countryCode: "NA",
		currencyName: "Dollar",
	},
	{
		currency: "NGN",
		country: "Naira (Nigeria)",
		symbol: "₦",
		countryCode: "NG",
		currencyName: "Naira",
	},
	{
		currency: "NIO",
		country: "Córdoba (Nicaragua)",
		symbol: "C$",
		countryCode: "NI",
		currencyName: "Córdoba",
	},
	{
		currency: "NOK",
		country: "Krone (Norway)",
		symbol: "kr",
		countryCode: "NO",
		currencyName: "Krone",
	},
	{
		currency: "NZD",
		country: "Dollar (New Zealand)",
		symbol: "$",
		countryCode: "NZ",
		currencyName: "Dollar",
	},
	{
		currency: "OMR",
		country: "Rial (Oman)",
		symbol: "ر.ع.",
		countryCode: "OM",
		currencyName: "Rial",
	},
	{
		currency: "PAB",
		country: "Balboa (Panama)",
		symbol: "B/. ",
		countryCode: "PA",
		currencyName: "Balboa",
	},
	{
		currency: "PEN",
		country: "Sol (Peru)",
		symbol: "S/.",
		countryCode: "PE",
		currencyName: "Sol",
	},
	{
		currency: "PGK",
		country: "Kina (New Guinea)",
		symbol: "K",
		countryCode: "PG",
		currencyName: "Kina",
	},
	{
		currency: "PHP",
		country: "Peso (Philippines)",
		symbol: "₱",
		countryCode: "PH",
		currencyName: "Peso",
	},
	{
		currency: "PKR",
		country: "Rupee (Pakistan)",
		symbol: "Rs",
		countryCode: "PK",
		currencyName: "Rupee",
	},
	{
		currency: "PLN",
		country: "Zloty (Poland)",
		symbol: "zł",
		countryCode: "PL",
		currencyName: "Zloty",
	},
	{
		currency: "PYG",
		country: "Guarani (Paraguay)",
		symbol: "₲",
		countryCode: "PY",
		currencyName: "Guarani",
	},
	{
		currency: "QAR",
		country: "Riyal (Qatar)",
		symbol: "ر.ق",
		countryCode: "QA",
		currencyName: "Riyal",
	},
	{
		currency: "RON",
		country: "Leu (Romania)",
		symbol: "lei",
		countryCode: "RO",
		currencyName: "Leu",
	},
	{
		currency: "RSD",
		country: "Dinar (Serbia)",
		symbol: "дин.",
		countryCode: "RS",
		currencyName: "Dinar",
	},
	{
		currency: "RUB",
		country: "Ruble (Russia)",
		symbol: "₽",
		countryCode: "RU",
		currencyName: "Ruble",
	},
	{
		currency: "RWF",
		country: "Franc (Rwanda)",
		symbol: "RF",
		countryCode: "RW",
		currencyName: "Franc",
	},
	{
		currency: "SAR",
		country: "Riyal (Saudi Arabia)",
		symbol: "ر.س",
		countryCode: "SA",
		currencyName: "Riyal",
	},
	{
		currency: "SBD",
		country: "Dollar (Solomon)",
		symbol: "$",
		countryCode: "SB",
		currencyName: "Dollar",
	},
	{
		currency: "SCR",
		country: "Rupee (Seychelles)",
		symbol: "₨",
		countryCode: "SC",
		currencyName: "Rupee",
	},
	{
		currency: "SDG",
		country: "Pound (Sudan)",
		symbol: "ج.س",
		countryCode: "SD",
		currencyName: "Pound",
	},
	{
		currency: "SEK",
		country: "Krona (Sweden)",
		symbol: "kr",
		countryCode: "SE",
		currencyName: "Krona",
	},
	{
		currency: "SGD",
		country: "Dollar (Singapore)",
		symbol: "$",
		countryCode: "SG",
		currencyName: "Dollar",
	},
	{
		currency: "SHP",
		country: "Pound (Saint Helena)",
		symbol: "£",
		countryCode: "SH",
		currencyName: "Pound",
	},
	{
		currency: "SLL",
		country: "Leone (Sierra Leone)",
		symbol: "Le",
		countryCode: "SL",
		currencyName: "Leone",
	},
	{
		currency: "SOS",
		country: "Shilling (Somalia)",
		symbol: "S",
		countryCode: "SO",
		currencyName: "Shilling",
	},
	{
		currency: "SRD",
		country: "Dollar (Suriname)",
		symbol: "$",
		countryCode: "SR",
		currencyName: "Dollar",
	},
	{
		currency: "SSP",
		country: "Pound (South Sudan)",
		symbol: "£",
		countryCode: "SS",
		currencyName: "Pound",
	},
	{
		currency: "STN",
		country: "Dobra (São Tomé)",
		symbol: "Db",
		countryCode: "ST",
		currencyName: "Dobra",
	},
	{
		currency: "SYP",
		country: "Pound (Syria)",
		symbol: "ل.س",
		countryCode: "SY",
		currencyName: "Pound",
	},
	{
		currency: "SZL",
		country: "Lilangeni (Eswatini)",
		symbol: "E",
		countryCode: "SZ",
		currencyName: "Lilangeni",
	},
	{
		currency: "THB",
		country: "Baht (Thailand)",
		symbol: "฿",
		countryCode: "TH",
		currencyName: "Baht",
	},
	{
		currency: "TJS",
		country: "Somoni (Tajikistan)",
		symbol: "SM",
		countryCode: "TJ",
		currencyName: "Somoni",
	},
	{
		currency: "TMT",
		country: "Manat (Turkmenistan)",
		symbol: "m",
		countryCode: "TM",
		currencyName: "Manat",
	},
	{
		currency: "TND",
		country: "Dinar (Tunisia)",
		symbol: "د.ت",
		countryCode: "TN",
		currencyName: "Dinar",
	},
	{
		currency: "TOP",
		country: "Panga (Tonga)",
		symbol: "T$",
		countryCode: "TO",
		currencyName: "Panga",
	},
	{
		currency: "TRY",
		country: "Lira (Turkey)",
		symbol: "₺",
		countryCode: "TR",
		currencyName: "Lira",
	},
	{
		currency: "TTD",
		country: "Dollar (Trinidad)",
		symbol: "$",
		countryCode: "TT",
		currencyName: "Dollar",
	},
	{
		currency: "TWD",
		country: "Dollar (Taiwan)",
		symbol: "NT$",
		countryCode: "TW",
		currencyName: "Dollar",
	},
	{
		currency: "TZS",
		country: "Shilling (Tanzania)",
		symbol: "TSh",
		countryCode: "TZ",
		currencyName: "Shilling",
	},
	{
		currency: "UAH",
		country: "Hryvnia (Ukraine)",
		symbol: "₴",
		countryCode: "UA",
		currencyName: "Hryvnia",
	},
	{
		currency: "UGX",
		country: "Shilling (Uganda)",
		symbol: "USh",
		countryCode: "UG",
		currencyName: "Shilling",
	},
	{
		currency: "UYU",
		country: "Peso (Uruguay)",
		symbol: "$U",
		countryCode: "UY",
		currencyName: "Peso",
	},
	{
		currency: "UZS",
		country: "Som (Uzbekistan)",
		symbol: "лв",
		countryCode: "UZ",
		currencyName: "Som",
	},
	{
		currency: "VEF",
		country: "Bolívar (Venezuela)",
		symbol: "Bs.S",
		countryCode: "VE",
		currencyName: "Bolívar",
	},
	{
		currency: "VND",
		country: "Dong (Vietnam)",
		symbol: "₫",
		countryCode: "VN",
		currencyName: "Dong",
	},
	{
		currency: "VUV",
		country: "Vatu (Vanuatu)",
		symbol: "Vt",
		countryCode: "VU",
		currencyName: "Vatu",
	},
	{
		currency: "WST",
		country: "Tala (Samoa)",
		symbol: "T",
		countryCode: "WS",
		currencyName: "Tala",
	},
	{
		currency: "YER",
		country: "Rial (Yemen)",
		symbol: "ر.ي",
		countryCode: "YE",
		currencyName: "Rial",
	},
	{
		currency: "ZAR",
		country: "Rand (South Africa)",
		symbol: "R",
		countryCode: "ZA",
		currencyName: "Rand",
	},
	{
		currency: "ZMW",
		country: "Kwacha (Zambia)",
		symbol: "ZK",
		countryCode: "ZM",
		currencyName: "Kwacha",
	},
	{
		currency: "ZWL",
		country: "Dollar (Zimbabwe)",
		symbol: "$",
		countryCode: "ZW",
		currencyName: "Dollar",
	},
];
